package questions;

public class Snippet {
	EDUCATION 
	 
	HINDUSTAN COLLEGE OF ARTS AND SCIENCE COIMBATORE                 2024       
	 
	BSC- INFORMATION TECHNOLOGY 
	 
	PERCENTAGE- 68.10% 
		VIVEKANANDA VIDYALAYA MATRIC HIGHER SECONDARY SCHOOL   2021 	         
	HSC   
	PERCENTAGE- 85.00% 
	VIVEKANANDA VIDYALAYA MATRIC HIGHER SECONDARY SCHOOL   2019           
	SSLC 
	
}

